# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/mukeshydv/SwipePopNavigation.git'
target 'SwipePopNavigationDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwipePopNavigationDemo
	pod 'SwipePopNavigation', :path => '../'
end
